-- ═══════════════════════════════════════════════════════════════
-- migration_staff.sql · תיק אישי לאיש צוות (2026-08-20, בקשת יוסף)
--
-- טבלת `staff` מחזיקה את הפרטים המנהליים של אנשי הצוות: מספר עובד, ת"ז,
-- כתובת, תאריך לידה, פרטי בנק לתשלום משכורת, ואילו מסמכים הוגשו.
--
-- ⚠️ זו הטבלה הרגישה ביותר במערכת — פרטי חשבון בנק ותעודות זהות של עובדים.
-- לכן, בניגוד לכל שאר הטבלאות: **מנהל בלבד**, גם קריאה וגם כתיבה. אין כאן
-- הרשאה מדורגת לפי כיתה, ואין גישה לצוות רגיל.
--
-- הקישור ל-`profiles` הוא אופציונלי (`user_id`): יש אנשי צוות ברשימה שאין
-- להם עדיין חשבון במערכת, והרשומה צריכה להתקיים גם בלעדיו.
-- אידמפוטנטי.
-- ═══════════════════════════════════════════════════════════════

create table if not exists public.staff (
  id            bigint generated by default as identity primary key,
  user_id       uuid references public.profiles(id) on delete set null,
  emp_no        text,                 -- מספר עובד
  first_name    text not null,
  last_name     text,
  phone         text,
  home_phone    text,
  tz            text,                 -- תעודת זהות
  email         text,
  doc_kind      text,                 -- ת.ז. / דרכון
  birthdate     date,
  address       text,
  bank_no       text,                 -- מספר בנק
  branch_no     text,                 -- סניף
  account_no    text,                 -- מספר חשבון
  has_cert      boolean,              -- הוגשה תעודה
  has_id_copy   boolean,              -- הוגש צילום ת"ז
  role_label    text,                 -- תפקיד חופשי (מחנך/מלמד/מזכירות…)
  active        boolean not null default true,
  note          text,
  drive_id      text,                 -- תיקיית התיק האישי בדרייב
  drive_url     text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index if not exists staff_emp_no_uidx on public.staff(emp_no) where emp_no is not null and emp_no <> '';
create unique index if not exists staff_tz_uidx     on public.staff(tz)     where tz is not null and tz <> '';
create index        if not exists staff_user_idx    on public.staff(user_id);

alter table public.staff enable row level security;

-- מנהל בלבד — פרטי בנק ות"ז של עובדים אינם עניינו של צוות אחר
drop policy if exists staff_admin_all on public.staff;
create policy staff_admin_all on public.staff for all to authenticated
  using ( public.is_admin() ) with check ( public.is_admin() );

-- שמירת updated_at
create or replace function public.staff_touch() returns trigger
  language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists staff_touch_trg on public.staff;
create trigger staff_touch_trg before update on public.staff
  for each row execute function public.staff_touch();
