-- ═══════════════════════════════════════════════════════════════
-- migration_staff_salary.sql · ניהול שכר צוות (2026-08-30, בקשת יוסף)
--
-- טבלת `staff_salary` מחזיקה את פרטי השכר של אנשי הצוות: סכום בסיס, השלמה,
-- נסיעות, ביגוד והבראה, פנסיה, קרן השתלמות, שעות ותוספות חודשיות.
--
-- ⚠️ טבלה נפרדת מ-`staff` (ולא עמודות עליה) בכוונה: אדם אחד יכול לקבל שכר
-- משני מוסדות (בית התלמוד + משמרת חיים) — שורה לכל מוסד. `staff_id` אופציונלי
-- כדי לתמוך גם בשמות שעדיין אינם רשומים בטבלת הצוות (`person_name`).
--
-- ⚠️ פרטי שכר רגישים כמו פרטי בנק ב-`staff`. RLS = **מנהל בלבד**, קריאה וכתיבה.
-- אידמפוטנטי.
-- ═══════════════════════════════════════════════════════════════

create table if not exists public.staff_salary (
  id            bigint generated by default as identity primary key,
  staff_id      bigint references public.staff(id) on delete set null,
  person_name   text,                 -- שם, כשאין קישור לטבלת הצוות
  institution   text,                 -- בית התלמוד / משמרת חיים
  role_label    text,                 -- תפקיד
  amount        numeric default 0,    -- סכום בסיס
  supplement    numeric default 0,    -- השלמה
  travel        text,                 -- נסיעות (מגולם / תוספת / סכום)
  clothing      text,                 -- ביגוד והבראה
  pension       boolean,              -- פנסיה
  study_fund    boolean,              -- קרן השתלמות
  hours         numeric,              -- שעות
  additions     jsonb not null default '[]'::jsonb,  -- תוספות חודשיות [{label, amount}]
  note          text,                 -- הערות
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists staff_salary_staff_idx on public.staff_salary(staff_id);

alter table public.staff_salary enable row level security;

-- מנהל בלבד — שכר עובדים אינו עניינו של צוות אחר
drop policy if exists staff_salary_admin_all on public.staff_salary;
create policy staff_salary_admin_all on public.staff_salary for all to authenticated
  using ( public.is_admin() ) with check ( public.is_admin() );

-- שמירת updated_at
drop trigger if exists staff_salary_touch_trg on public.staff_salary;
create trigger staff_salary_touch_trg before update on public.staff_salary
  for each row execute function public.staff_touch();
