-- ═══════════════════════════════════════════════════════════════
-- migration_student_docs.sql · "תיק המסמכים" של התלמיד (2026-08-20, בקשת יוסף)
--
-- מה זה פותר: האפיון של "תיק תל"א" דורש ארבעה מסמכים סרוקים לכל תלמיד
-- (ויתור סודיות · מסמך קביל · שאלון הפניה · אבחונים ורקע קודם), ולמערכת
-- לא היתה שום דרך לצרף קובץ לתלמיד — לא היה אפילו bucket אחד ב-Storage.
--
-- מודל: טבלה אחת מחזיקה גם קבצים שהועלו למערכת (source='upload', יושבים
-- ב-bucket פרטי) וגם מסמכים שכבר קיימים בגוגל דרייב (source='drive', רק
-- קישור). כך "תיק המסמכים" בכרטיס מציג הכל במקום אחד.
--
-- אבטחה: אלו המסמכים הרגישים ביותר במערכת (אבחונים פסיכולוגיים, ויתור
-- סודיות). ה-bucket פרטי, ההורדה רק בקישור חתום זמני, וה-RLS מצמצם
-- לפי מודל ההרשאות הקיים: מנהל, או מי שיש לו גישה לכיתת התלמיד.
-- אידמפוטנטי — בטוח להריץ שוב.
-- ═══════════════════════════════════════════════════════════════

-- ===== הטבלה =====
create table if not exists public.student_docs (
  id           bigint generated by default as identity primary key,
  student_id   bigint not null references public.students(id) on delete cascade,
  kind         text   not null default 'אחר',   -- קטגוריית האפיון
  folder       text   not null default '',      -- תת-תיקייה בתוך התיק (ריק = שורש)
  title        text   not null,
  source       text   not null default 'upload' check (source in ('upload','drive')),
  path         text,            -- source=upload: הנתיב ב-bucket student-docs
  drive_id     text,            -- source=drive: מזהה הקובץ בדרייב
  drive_url    text,            -- source=drive: קישור לצפייה
  mime         text,
  size_bytes   bigint,
  note         text,
  created_by   uuid default auth.uid() references public.profiles(id),
  created_at   timestamptz not null default now(),
  constraint student_docs_payload check (
    (source = 'upload' and path is not null) or
    (source = 'drive'  and coalesce(drive_id, drive_url) is not null)
  )
);
create index if not exists student_docs_student_idx on public.student_docs(student_id);
create unique index if not exists student_docs_path_uidx on public.student_docs(path) where path is not null;
-- אינדוקס חוזר של הדרייב לא ייצור כפילויות
create unique index if not exists student_docs_drive_uidx
  on public.student_docs(student_id, drive_id) where drive_id is not null;

alter table public.student_docs enable row level security;

-- קריאה/הוספה: מנהל, או מי שרשאי לראות את התלמיד (כיתה משויכת)
drop policy if exists sdoc_read on public.student_docs;
create policy sdoc_read on public.student_docs for select to authenticated
  using ( public.can_read_student(student_id) );

drop policy if exists sdoc_ins on public.student_docs;
create policy sdoc_ins on public.student_docs for insert to authenticated
  with check ( public.is_staff() and public.can_read_student(student_id) );

-- עדכון/מחיקה: מנהל, או מי שהעלה את המסמך בעצמו
drop policy if exists sdoc_upd on public.student_docs;
create policy sdoc_upd on public.student_docs for update to authenticated
  using ( public.is_admin() or created_by = auth.uid() )
  with check ( public.is_admin() or created_by = auth.uid() );

drop policy if exists sdoc_del on public.student_docs;
create policy sdoc_del on public.student_docs for delete to authenticated
  using ( public.is_admin() or created_by = auth.uid() );

-- ===== Storage: bucket פרטי =====
insert into storage.buckets (id, name, public)
  values ('student-docs', 'student-docs', false)
  on conflict (id) do nothing;

-- מוסכמת נתיב: {student_id}/{uuid}-{שם קובץ} → התיקייה הראשונה היא מזהה התלמיד,
-- וכך אפשר לאכוף את אותה הרשאה גם על הקבצים עצמם ולא רק על השורות.
drop policy if exists sdoc_obj_read on storage.objects;
create policy sdoc_obj_read on storage.objects for select to authenticated
  using ( bucket_id = 'student-docs'
          and public.can_read_student(((storage.foldername(name))[1])::bigint) );

drop policy if exists sdoc_obj_ins on storage.objects;
create policy sdoc_obj_ins on storage.objects for insert to authenticated
  with check ( bucket_id = 'student-docs'
               and public.is_staff()
               and public.can_read_student(((storage.foldername(name))[1])::bigint) );

drop policy if exists sdoc_obj_del on storage.objects;
create policy sdoc_obj_del on storage.objects for delete to authenticated
  using ( bucket_id = 'student-docs'
          and (public.is_admin() or owner = auth.uid()) );
